apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # This fixes the port so you can easily access it